const $ = id => document.getElementById(id);
const canvas = $('stage'); let ctx = canvas.getContext('2d');
const C = {bg:'#07131d',panel:'#10212f',line:'#294150',text:'#eef5fa',muted:'#a8bdcc',teal:'#61dac8',gold:'#ffd176',pink:'#ef65bf',salmon:'#ff987e',blue:'#75baff'};
const baseStories = await fetch('storyboards.json').then(r=>r.json());
let stories=structuredClone(baseStories),locale='en',dictionary=(await fetch('locales/en.json').then(r=>r.json())).labels,webAssets=null;
try{const r=await fetch('web/manifest.json');if(r.ok)webAssets=await r.json();}catch{}
function tr(s){s=String(s);if(dictionary[s])return dictionary[s];for(const [pattern,replacement] of dictionary.$patterns||[])s=s.replace(new RegExp(pattern,'g'),replacement);return s;}
async function configure(options={}){stop();locale=options.locale||'en';dictionary=options.labels||(await fetch('locales/en.json').then(r=>r.json())).labels;stories=structuredClone(options.stories||baseStories);document.documentElement.lang=locale;await select(id);}
const cache = new Map();
let id='segmentation', data, story, time=0, playing=false, last=0, manual={}, chosenStep=-1;
function text(s,x,y,size=20,color=C.text,weight=400){s=tr(s);ctx.fillStyle=color;ctx.font=`${weight} ${size}px Arial, sans-serif`;ctx.textBaseline='top';ctx.fillText(String(s),x,y);}
function wrap(s,x,y,w,size=20,color=C.text,line=size*1.35,weight=400){s=tr(s);ctx.font=`${weight} ${size}px Arial, sans-serif`;const cjk=/[\u3400-\u9fff]/.test(s),join=cjk?'':' ';let row='',yy=y;for(const word of cjk?Array.from(s):String(s).split(/\s+/)){const candidate=row?row+join+word:word;if(row&&ctx.measureText(candidate).width>w){text(row,x,yy,size,color,weight);yy+=line;row=word;}else row=candidate;}if(row)text(row,x,yy,size,color,weight);return yy+line;}
function box(x,y,w,h,fill=C.panel,r=14){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function line(points,color,width=2){if(!points.length)return;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.stroke();}
function dot(p,color,r=4){ctx.fillStyle=color;ctx.beginPath();ctx.arc(p[0],p[1],r,0,Math.PI*2);ctx.fill();}
function contain(im,x,y,w,h){const s=Math.min(w/im.width,h/im.height),ww=im.width*s,hh=im.height*s;ctx.drawImage(im,x+(w-ww)/2,y+(h-hh)/2,ww,hh);return [x+(w-ww)/2,y+(h-hh)/2,ww,hh];}
function img(name){return data.images[name];}
function project(points,rect,center,radius,yaw=.35,pitch=.18){const [x,y,w,h]=rect,scale=Math.min(w,h)*.46/radius,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);return points.map(p=>{const a=p[0]-center[0],b=p[1]-center[1],c=p[2]-center[2];return [x+w/2+(cy*a+sy*b)*scale,y+h/2+(-sp*sy*a+sp*cy*b-cp*c)*scale,cp*sy*a-cp*cy*b-sp*c];});}
function rawMesh(points,faces,rect,center,radius,color,yaw=.35,pitch=.18,alpha=1){const pp=project(points,rect,center,radius,yaw,pitch),rgb=color.match(/\w\w/g).map(v=>parseInt(v,16));const sorted=faces.map(f=>[f,(pp[f[0]][2]+pp[f[1]][2]+pp[f[2]][2])/3]).sort((a,b)=>a[1]-b[1]);ctx.save();ctx.globalAlpha=alpha;for(const [f]of sorted){const a=pp[f[0]],b=pp[f[1]],c=pp[f[2]],u=b.map((v,i)=>v-a[i]),v=c.map((v,i)=>v-a[i]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],len=Math.hypot(...n)||1;const light=.36+.64*Math.abs((n[0]*-.3+n[1]*-.4+n[2]*.866)/len);ctx.fillStyle=`rgb(${rgb.map(v=>Math.round(v*light)).join(',')})`;ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.lineTo(c[0],c[1]);ctx.closePath();ctx.fill();}ctx.restore();return pp;}
const meshCache = new WeakMap();
function mesh(points,faces,rect,center,radius,color,yaw=.35,pitch=.18,alpha=1){
 const [x,y,w,h]=rect,key=JSON.stringify([w,h,center,radius,color,yaw,pitch,alpha]);let entries=meshCache.get(points);if(!entries){entries=new Map();meshCache.set(points,entries);}let layer=entries.get(key);
 if(!layer){layer=document.createElement('canvas');layer.width=Math.ceil(w);layer.height=Math.ceil(h);const saved=ctx;try{ctx=layer.getContext('2d');rawMesh(points,faces,[0,0,w,h],center,radius,color,yaw,pitch,alpha);}finally{ctx=saved;}if(entries.size>5)entries.clear();entries.set(key,layer);}ctx.drawImage(layer,x,y);
}
function label(s,x,y,color=C.muted,size=17){text(s,x,y,size,color,600);}
function tag(s,x,y,color=C.teal,size=17){s=tr(s);ctx.font=`600 ${size}px Arial`;const w=ctx.measureText(s).width+24;box(x,y,w,size+17,C.bg,6);text(s,x+12,y+8,size,color,600);return w;}
function fraction(start,end){return Math.max(0,Math.min(1,(time-start)/(end-start)));}
function renderSeg(rect,step,portrait){const [x,y,w,h]=rect,n=data.frames.length;let frame=step===1?data.hero:step===3?data.pointFrame:Math.floor((.12+.76*(.5-.5*Math.cos(time*Math.PI/4)))*(n-1));if(manual.position!=null)frame=Math.round(manual.position*(n-1));const f=data.frames[frame];const gap=portrait?18:24,pw=(w-gap)/2,imH=portrait?pw:h-89;const top=portrait?y+78:y+42;
 let states=step===0?['before','before']:step===1?['before','after']:step===2?['after','region']:['after','after'];if(manual.state)states[1]=manual.state;
 if(step===0){const imW=portrait?w-200:h-72;const ix=portrait?x+100:x+55,iy=y+32;const r=contain(img(f.images.before),ix,iy,imW,imW);label('Original labels · axial CT',ix,iy-25,C.text,portrait?20:18);if(portrait){label('Pancreas',x+70,iy+imW+25,C.salmon,22);label('Duodenum',x+315,iy+imW+25,C.blue,22);wrap('Two neighboring organs. The task is to audit which organ owns each piece of labeled tissue.',x+35,iy+imW+78,w-70,25,C.muted);}else{label('PANCREAS',x+460,y+82,C.salmon,22);label('DUODENUM',x+460,y+128,C.blue,22);wrap('Audit tissue ownership in a 3D scan.',x+460,y+190,w-500,29,C.text,38,600);wrap('Shown: two of the 13 supplied organ masks.',x+460,y+285,w-500,19,C.muted);}return;}
 for(let j=0;j<2;j++){const xx=x+j*(pw+gap);label(j===0?(step===1?'Original labels':'Reassigned labels'):(manual.state?{before:'Original labels',after:'Reassigned labels',region:'Transferred region'}[manual.state]:step===1?'After the edit':step===2?'Transferred tissue':'Focused audit point'),xx,top-32,C.text,portrait?19:20);const r=contain(img(f.images[states[j]]),xx,top,pw,imH);if(step===3&&j===1&&frame===data.pointFrame){const p=[r[0]+data.pointUV[0]*r[2],r[1]+data.pointUV[1]*r[3]];ctx.strokeStyle=C.gold;ctx.lineWidth=3;ctx.beginPath();ctx.arc(...p,13,0,Math.PI*2);ctx.stroke();line([[p[0]-22,p[1]],[p[0]+22,p[1]]],C.gold,2);line([[p[0],p[1]-22],[p[0],p[1]+22]],C.gold,2);}}
 const bottom=top+imH+15;label(`Same physical plane · z = ${f.z_mm.toFixed(1)} mm (LPS)`,x,bottom,C.muted,portrait?19:16);
 if(portrait){const yy=bottom+58;label(step===1?'21.04 mL reassigned':step===2?'Yellow = transferred region':'Broad audit: missed',x+12,yy,step===2?C.gold:C.teal,28);if(step===3){label('Focused audit: found',x+12,yy+48,C.gold,28);wrap('Accepted point near the reassigned pancreas tissue. One Sol attempt per scope.',x+12,yy+112,w-24,24,C.muted);}else{wrap(step===1?'Pancreas → duodenum. Both pictures use the exact same CT and slice.':'Move through the stack to see that this is a 3D region, not a single-pixel mistake.',x+12,yy+62,w-24,25,C.muted);}}
 else if(step===3){tag('Broad: missed',x+w-370,y+h-40,C.muted);tag('Focused: found',x+w-187,y+h-40,C.gold);}else tag(step===1?'21.04 mL reassigned':'Yellow = transferred tissue',x+w-300,y+h-40,C.gold);
}
function renderVessel(rect,step,portrait){const[x,y,w,h]=rect;let k=Math.round((manual.position??fraction(16,27.5))*(data.path.length-1));if(step<2&&manual.position==null)k=data.gap_index;const angle=Number(manual.angle??0),yaw=.35+(manual.rotation??0);const mr=portrait?[x,y+35,w,h*.40]:[x,y+30,w*.57,h-45];box(...mr,'#0b1c28');const source=step===0?data.before:data.after;mesh(source.points,source.faces,mr,data.center,data.radius,'70a69f',yaw,.25);
 const pp=project(data.path,mr,data.center,data.radius,yaw,.25);if(step>0){line(pp,C.gold,2.8);const ap=project(data.added,mr,data.center,data.radius,yaw,.25);ap.forEach(p=>dot(p,C.pink,2.6));}else{dot(pp[data.gap_index],C.pink,8);ctx.strokeStyle=C.pink;ctx.lineWidth=2;ctx.beginPath();ctx.arc(pp[data.gap_index][0],pp[data.gap_index][1],18,0,Math.PI*2);ctx.stroke();}
 label(step===0?'Supplied vessel segmentation':'Saved repaired geometry',mr[0]+15,mr[1]+12,C.text,18);label('Display mesh simplified',mr[0]+15,mr[1]+mr[3]-24,C.muted,14);
 if(step>=2){const p=data.path[k],a=data.normal[k],b=data.binormal[k],corners=[[-8,-8],[8,-8],[8,8],[-8,8],[-8,-8]].map(([u,v])=>p.map((q,j)=>q+u*a[j]+v*b[j]));line(project(corners,mr,data.center,data.radius,yaw,.25),C.teal,2);dot(pp[k],C.teal,5);}
 const rx=portrait?x:x+w*.60,ry=portrait?y+h*.42:y+38,rw=portrait?w:w*.40;
 if(step<2){label(step===0?'An internal gap':'103 voxels added',rx+15,ry+28,step===0?C.pink:C.teal,portrait?30:28);wrap(step===0?'The review region narrows the search. The agent must restore the connection and extract a usable route.':'Magenta: added voxels\nGold: the extracted centerline',rx+15,ry+85,rw-30,portrait?25:23,C.muted);wrap('Coronary vessel geometry from a retained CT case.',rx+15,ry+(portrait?240:228),rw-30,18,C.muted);return;}
 const cutIndex=data.cut_indices.reduce((best,q,i)=>Math.abs(q-k)<Math.abs(data.cut_indices[best]-k)?i:best,0);const cutSize=100;box(rx+8,ry+26,cutSize+12,cutSize+12,C.bg);contain(img(data.cuts[cutIndex]),rx+14,ry+32,cutSize,cutSize);label('Linked CT section',rx+cutSize+38,ry+40,C.teal,portrait?21:18);wrap(`${data.arc[k].toFixed(1)} mm along the route`,rx+cutSize+38,ry+76,rw-cutSize-45,portrait?22:18,C.text);label(`CPR rotation ${angle*45}°`,rx+cutSize+38,ry+115,C.muted,16);
 const cy=ry+cutSize+66,cw=rw-24,ch=portrait?100:91;const ci=img(data.cpr[angle]);box(rx+12,cy,cw,ch,C.bg,4);ctx.save();ctx.beginPath();ctx.rect(rx+12,cy,cw*(step===2?(k+1)/data.path.length:1),ch);ctx.clip();ctx.drawImage(ci,rx+12,cy,cw,ch);ctx.restore();line([[rx+12+cw*k/(data.path.length-1),cy],[rx+12+cw*k/(data.path.length-1),cy+ch]],C.teal,2);label('0',rx+12,cy+ch+9,C.muted,15);label(`${data.saved_line_length_mm.toFixed(1)} mm`,rx+cw-56,cy+ch+9,C.muted,15);label('Curved planar reformation (CPR)',rx+12,cy-27,C.text,18);
 if(step===3){const yy=portrait?cy+ch+53:cy+ch+38;text('184.81 → 175.92 mm',rx+12,yy,portrait?27:24,C.gold,600);if(portrait)label('Author corrected the distance metadata',rx+12,yy+36,C.muted,19);}else if(portrait)wrap('The turquoise section and cursor refer to the same position along the 3D route.',rx+12,cy+ch+62,rw-24,22,C.muted);
}
function curve(rect,phase){const[x,y,w,h]=rect;label(`Example regional radial strain · region ${data.curve.region}`,x,y,C.text,17);const pad=48,g=[x+pad,y+32,w-pad-12,h-66],values=[...data.curve.reference,...data.curve.prediction],lo=Math.min(0,...values)-2,hi=Math.max(...values)+2;line([[g[0],g[1]],[g[0],g[1]+g[3]],[g[0]+g[2],g[1]+g[3]]],C.line,1);text(`${Math.round(hi)}%`,x,y+32,14,C.muted);text(`${Math.round(lo)}%`,x,y+h-44,14,C.muted);for(const key of ['reference','prediction'])line(data.curve[key].map((v,i)=>[g[0]+g[2]*i/29,g[1]+(hi-v)/(hi-lo)*g[3]]),key==='reference'?C.gold:C.teal,2.5);line([[g[0]+g[2]*phase/29,g[1]],[g[0]+g[2]*phase/29,g[1]+g[3]]],C.text,1);label('Simulation reference',x+pad,y+h-22,C.gold,14);label('Reconstruction',x+w*.58,y+h-22,C.teal,14);}
function cylinders(rect,portrait){const[x,y,w,h]=rect;label('CONCEPTUAL ILLUSTRATION',x+15,y+8,C.gold,18);const cy=y+(portrait?260:148),rh=portrait?210:160,rw=portrait?104:142,centers=[x+w*.25,x+w*.75],amount=Math.sin(time*1.15)*1.35;for(let side=0;side<2;side++){const cx=centers[side];ctx.strokeStyle=C.muted;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(cx,cy-rh/2,rw,25,0,0,Math.PI*2);ctx.ellipse(cx,cy+rh/2,rw,25,0,0,Math.PI*2);ctx.stroke();line([[cx-rw,cy-rh/2],[cx-rw,cy+rh/2]],C.muted,2);line([[cx+rw,cy-rh/2],[cx+rw,cy+rh/2]],C.muted,2);for(let j=0;j<5;j++){const yy=cy-rh/2+rh*j/4,a=(side?amount*(j/4-.5)*2:0);for(let q=0;q<3;q++){const ang=a+q*2*Math.PI/3,p=[cx+rw*.7*Math.cos(ang),yy+18*Math.sin(ang)];dot(p,[C.teal,C.gold,C.pink][q],7);if(j<4){const a2=side?amount*((j+1)/4-.5)*2:0,p2=[cx+rw*.7*Math.cos(a2+q*2*Math.PI/3),cy-rh/2+rh*(j+1)/4+18*Math.sin(a2+q*2*Math.PI/3)];line([p,p2],[C.teal,C.gold,C.pink][q],2);}}}label(side?'Internal twist':'No internal twist',cx-rw,cy+rh/2+26,C.text,portrait?21:23);}wrap('Same outer shape. Different material trajectories.',x+15,y+h-(portrait?166:56),w-30,portrait?29:27,C.text,38,600);if(portrait)wrap('Dots represent material inside the shape. This diagram is not a reconstruction of the agent’s error.',x+15,y+h-86,w-30,23,C.muted);}
function renderCardiac(rect,step,portrait){if(step===4&&!Object.keys(manual).length)return cylinders(rect,portrait);const[x,y,w,h]=rect,phase=Math.min(29,Math.floor((manual.position??((time%4)/4))*30)),yaw=.35+(manual.rotation??0);const chartSide=step===3&&!portrait, modelH=portrait?h*.57:chartSide?h-25:h*.77,pw=((chartSide?w*.55:w)-20)/2;const rects=[[x,y+35,pw,modelH-38],[x+pw+20,y+35,pw,modelH-38]];label(`Acquired phase ${String(phase+1).padStart(2,'0')} / 30`,x,y+4,C.muted,16);
 if(step===0){label('Supplied mask slice',x+12,y+45,C.gold,portrait?19:18);contain(img(data.masks[phase]),x+30,y+81,pw-60,modelH-107);label('Sol reconstruction',x+pw+30,y+45,C.teal,portrait?19:18);mesh(data.models[0].points[phase],data.models[0].faces,rects[1],data.center,data.radius,'61dac8',yaw);wrap('Binary wall masks are inputs. Sol must create the mesh and carry it through all 30 phases.',x+12,y+modelH+14,w-24,portrait?26:23,C.muted);return;}
 for(let side=0;side<2;side++){const model=data.models[side===0?1:0],color=side===0?C.gold:C.teal;mesh(model.points[phase],model.faces,rects[side],data.center,data.radius,side===0?'ffd176':'61dac8',yaw);label(side===0?'Simulation reference':'Sol reconstruction',rects[side][0]+12,y+42,color,portrait?18:19);if(step>=2){const tracks=data.material_tracks[side===0?'reference':'prediction'];for(let j=0;j<24;j++){const points=[];for(let p=Math.max(0,phase-4);p<=phase;p++)points.push(tracks[p][j]);const q=project(points,rects[side],data.center,data.radius,yaw);line(q,j%2?C.pink:C.blue,2);dot(q.at(-1),j%2?C.pink:C.blue,3.8);}}}
 const yy=y+modelH+12;if(step===3){curve(portrait?[x+12,yy,w-24,h-modelH-27]:[x+w*.57,y+65,w*.41,h-88],phase);}else{tag('Mean overlap 0.9461',x+12,yy,C.teal,portrait?22:20);if(portrait){wrap(step===2?'24 matched material probes. Both views share phase, camera and physical scale.':'The outer geometry follows the cycle. Does the material inside move correctly too?',x+12,yy+77,w-24,27,C.text);if(step===2)wrap('Markers are visible through the surfaces. They were selected by source order, not by error.',x+12,yy+200,w-24,22,C.muted);}else tag(step===2?'24 matched material probes':'Construction checks passed',x+w-378,yy,C.gold,18);}
}
function renderRegistration(rect,step,portrait){
 const[x,y,w,h]=rect,q=manual.position!=null?Math.min(7,Math.floor(manual.position*8)):step===3?5:3,plane=data.planes[Number(manual.plane??(step===1?Math.min(3,Math.floor((time-8)/2)):0))],method=step===0?'Sol / original 2D source':'Sol / full 3D source',m=data.methods[method];
 if(step<2)label(`${data.ids[q]} · ${plane}`,x+15,y+15,C.teal,19);
 if(step<2){const gap=portrait?8:22,pw=(w-gap*2-30)/3,ih=portrait?pw:Math.min(250,h-90),yy=y+(portrait?96:67);for(let j=0;j<3;j++){const xx=x+15+j*(pw+gap),im=[data.source[plane][q],data.manual[plane][q],m.images[plane][q]][j];label(['Source','Reference',step===0?'Earlier Sol':'Final Sol'][j],xx,yy-30,j===1?C.gold:C.teal,portrait?19:20);contain(img(im),xx,yy,pw,ih);}if(portrait){label(`${m.grade.per_point_mm[q].toFixed(2)} mm · 3D error`,x+20,yy+ih+45,C.gold,28);wrap('Each crop is centered on its own point. Compare local anatomy; read the score for physical distance.',x+20,yy+ih+110,w-40,27,C.text);wrap('Pause to select a query or another image plane.',x+20,y+h-95,w-40,23,C.muted);}else label('Independently centered crops · 62.4 mm field of view',x+20,y+h-29,C.muted,17);return;}
 const a=data.methods['Sol / original 2D source'].grade.per_point_mm,b=data.methods['Sol / full 3D source'].grade.per_point_mm,scale=step===3?8:35,left=x+90,right=x+w-100,top=y+60,row=portrait?58:31;
 label('Earlier 2D source',x+20,y+15,C.muted,18);label('Full 3D source',x+w*.52,y+15,C.teal,18);
 for(let i=0;i<8;i++){const yy=top+i*row;label(data.ids[i],x+18,yy-5,i===q?C.gold:C.muted,18);if(step===2){ctx.fillStyle=C.line;ctx.fillRect(left,yy,Math.min(1,a[i]/scale)*(right-left),8);}ctx.fillStyle=i===5?C.pink:C.teal;ctx.fillRect(left,yy+11,Math.min(1,b[i]/scale)*(right-left)*(step===2?Math.min(1,(time-16)/2):1),9);text(b[i].toFixed(2),right+15,yy+3,18,i===5?C.pink:C.text);}
 const limit=left+5/scale*(right-left);line([[limit,top-10],[limit,top+7*row+25]],C.gold,2);label('5 mm limit',limit+6,top-31,C.gold,15);if(portrait){wrap(step===3?'q06 exceeds the limit. Seven other points are within 2.2 mm.':'The long gray bars show the earlier misses. Teal and magenta show the final 3D-source result.',x+20,y+h-90,w-40,24,C.text);}else label(step===3?'Frozen failure · later visual acceptance recorded separately':'Fresh attempts: input information and strategy both changed',x+20,y+h-28,C.muted,17);
}
function renderLandmarks(rect,step,portrait){
 const[x,y,w,h]=rect,full=data.cases['ct-full'],crop=data.cases['ct-partial'],keys=['T4','T5','T6','L2'],key=manual.position!=null?keys[Math.min(3,Math.floor(manual.position*4))]:step===3?'T5':'T4',target=crop.targets[key],source=img(full.image),height=portrait?370:h-73,iw=height*full.aspect,xx=x+20,yy=y+35;
 label('Full CT · same sagittal plane',xx,y+10,C.muted,17);ctx.drawImage(source,xx,yy,iw,height);const cutoff=1-crop.shape[2]/full.shape[2],by=yy+height*cutoff,opacity=step===1?Math.min(1,(time-8)/2):1;
 if(step>0){ctx.fillStyle=`rgba(7,19,29,${.78*opacity})`;ctx.fillRect(xx,yy,iw,height*cutoff);line([[xx,by],[xx+iw,by]],C.gold,3);}const ref=full.targets[key].reference,p=[xx+ref.uv[0]*iw,yy+ref.uv[1]*height];dot(p,C.gold,5);label(key,p[0]+9,p[1]-10,C.gold,18);
 const rx=portrait?x+210:x+iw+65,rw=portrait?w-235:300,zy=y+55,zh=portrait?300:260,sx=95,sy=source.height-ref.ijk[2]-100,sw=190,sh=200,factor=Math.min(rw/sw,zh/sh),fy=factor*full.spacing[2]/full.spacing[1],dw=sw*factor,dh=sh*fy;
 ctx.drawImage(source,sx,sy,sw,sh,rx,zy,dw,dh);const boundary=zy+(source.height*cutoff-sy)*fy;
 if(step>0){ctx.fillStyle=`rgba(7,19,29,${.78*opacity})`;ctx.fillRect(rx,zy,dw,Math.max(0,Math.min(dh,boundary-zy)));if(boundary>=zy&&boundary<=zy+dh)line([[rx,boundary],[rx+dw,boundary]],C.gold,3);}
 const showPoint=(v,color)=>{if(!v?.ijk)return;const px=rx+(v.ijk[1]+.5-sx)*factor,py=zy+(source.height-v.ijk[2]-.5-sy)*fy;if(px<rx||px>rx+dw||py<zy||py>zy+dh)return;dot([px,py],color,6);};showPoint(ref,C.gold);if(step>=2)showPoint(target.predictions['terra-high'],C.pink);
 const infoY=portrait?y+425:y+65,infoX=portrait?x+20:rx+dw+40,infoW=portrait?w-40:x+w-infoX-22;
 if(step<2){wrap(step===0?'Find the named center, not just a plausible point in bone.':'The gray region lies outside the cropped task. T4 is above the cutoff; T5 is below it.',infoX,infoY,infoW,portrait?27:28,C.text);if(!portrait&&step===1)wrap('Actual crop boundary',infoX,infoY+165,infoW,22,C.gold);}
 else{wrap(`${key} · reference: ${target.reference.status==='observed'?'visible':'outside scan'}`,infoX,infoY,infoW,portrait?26:28,C.gold);label(`Terra: ${({observed:'point returned',out_of_fov:'outside scan',absent:'absent',uncertain:'uncertain'})[target.predictions['terra-high'].status]}`,infoX,infoY+(portrait?53:88),C.pink,portrait?23:25);label(`Sol: ${({observed:'point returned',out_of_fov:'outside scan',absent:'absent',uncertain:'uncertain'})[target.predictions['sol-xhigh'].status]}`,infoX,infoY+(portrait?93:136),C.teal,portrait?23:25);}
 if(portrait)wrap('Markers are projected. Distances are scored in 3D; this slice alone is not the reference.',x+20,y+h-75,w-40,22,C.muted);else label('Gold: reference / boundary · Magenta: Terra point',x+20,y+h-25,C.muted,16);
}
function draw(t,W=canvas.width,H=canvas.height){time=Math.max(0,Math.min(story.duration,t));if(canvas.width!==W||canvas.height!==H){canvas.width=W;canvas.height=H;}const portrait=H>W;ctx.fillStyle=C.bg;ctx.fillRect(0,0,W,H);const pad=portrait?40:42;label('MEDICAL IMAGE WORKFLOWS  /  '+({segmentation:'01',vessels:'02',cardiac:'03',registration:'04',landmarks:'05'}[id]),pad,portrait?38:26,C.teal,portrait?19:15);const titleBottom=wrap(story.title,pad,portrait?82:62,W-pad*2,portrait?43:39,C.text,portrait?51:47,700);wrap(story.subtitle,pad,titleBottom+10,W-pad*2,portrait?23:21,C.muted,30);
 const step=Math.max(0,story.steps.findLastIndex(s=>time>=s.at));const viz=portrait?[pad,265,W-pad*2,660]:[pad,165,W-pad*2,358];box(...viz);ctx.save();ctx.beginPath();ctx.roundRect(...viz,14);ctx.clip();const actualTime=time,base=baseStories[id],end=story.steps[step+1]?.at??story.duration,phase=(time-story.steps[step].at)/(end-story.steps[step].at);time=base.steps[step].at+phase*((base.steps[step+1]?.at??base.duration)-base.steps[step].at);({segmentation:renderSeg,vessels:renderVessel,cardiac:renderCardiac,registration:renderRegistration,landmarks:renderLandmarks}[id])(viz,step,portrait);time=actualTime;ctx.restore();
 const by=portrait?958:548;label(`0${step+1} / 0${story.steps.length}`,pad,by,C.teal,portrait?22:17);const tx=pad+(portrait?104:78);wrap(story.steps[step].title,tx,by,W-tx-pad,portrait?28:24,C.text,34,600);wrap(story.steps[step].caption,pad,by+(portrait?83:49),W-pad*2,portrait?25:23,C.text,portrait?34:31);
 const fy=H-(portrait?71:32);wrap(story.source,pad,fy,W-pad*2,portrait?15:13,C.muted,20);const progress=time/story.duration;ctx.fillStyle=C.line;ctx.fillRect(pad,H-12,W-pad*2,3);ctx.fillStyle=C.teal;ctx.fillRect(pad,H-12,(W-pad*2)*progress,3);canvas.setAttribute('aria-label',story.title+'. '+story.steps[step].caption);
 return step;
}
function ui(){const step=draw(time);$('timeline').value=time;$('clock').textContent=`${Math.floor(time/60)}:${String(Math.floor(time%60)).padStart(2,'0')} / 0:${story.duration}`;if(step!==chosenStep){chosenStep=step;$('caption').textContent=story.steps[step].caption;Array.from($('steps').children).forEach((b,i)=>b.setAttribute('aria-pressed',String(i===step)));}}
function stop(){playing=false;$('play').textContent='Play tour';}
function tick(stamp){if(playing){if(last)time+=Math.min(.15,(stamp-last)/1000);if(time>=story.duration){time=story.duration;stop();}ui();}last=stamp;requestAnimationFrame(tick);}
async function load(tour){if(cache.has(tour))return cache.get(tour);let d;if(webAssets?.json?.[tour]&&typeof DecompressionStream!=='undefined'){const r=await fetch(`web/${webAssets.json[tour]}`);d=await new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json();}else d=await fetch(`data/${tour}.json`).then(r=>r.json());let names=tour==='segmentation'?d.frames.flatMap(f=>Object.values(f.images)):tour==='vessels'?[...d.cpr,...d.cuts]:tour==='cardiac'?d.masks:d.image_files;d.images={};await Promise.all(names.map(async n=>{const im=new Image();im.src=webAssets?.images?.[n]?`web/${webAssets.images[n]}`:`data/${n}`;await im.decode();d.images[n]=im;}));cache.set(tour,d);return d;}
async function select(tour){if(!stories[tour])throw Error(`Unknown tour: ${tour}`);stop();$('status').textContent='Loading local source-derived data…';const loaded=await load(tour);id=tour;story=stories[id];data=loaded;time=0;manual={};chosenStep=-1;document.querySelectorAll('[data-tour]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tour===id)));$('timeline').max=story.duration;['play','replay','timeline'].forEach(x=>$(x).disabled=false);$('steps').replaceChildren(...story.steps.map((s,i)=>{const b=document.createElement('button');b.textContent=`${i+1}. ${s.title}`;b.onclick=()=>{stop();manual={};time=s.at;ui();};return b;}));$('state-label').hidden=id!=='segmentation';$('angle-label').hidden=id!=='vessels';$('rotation-label').hidden=!['vessels','cardiac'].includes(id);$('plane-label').style.display=id==='registration'?'flex':'none';// hidden must override flex labels
 for(const x of ['state-label','angle-label','rotation-label'])$(x).style.display=$(x).hidden?'none':'flex';$('position-name').textContent={segmentation:'Scan slice',vessels:'Route position',cardiac:'Cycle phase',registration:'Query point',landmarks:'Landmark: T4 / T5 / T6 / L2'}[id];$('rotation').value=0;$('angle').value=0;$('position').value=50;
 $('landscape-video').href=`exports/${id}-landscape.mp4`;$('portrait-video').href=`exports/${id}-portrait.mp4`;$('captions-link').href=`exports/${id}.vtt`;$('status').textContent='Ready · local data · no autoplay';ui();}
$('play').onclick=()=>{if(playing)stop();else{if(time>=story.duration)time=0;manual={};playing=true;last=0;$('play').textContent='Pause';}};$('replay').onclick=()=>{time=0;manual={};playing=true;last=0;$('play').textContent='Pause';ui();};$('timeline').oninput=e=>{stop();manual={};time=Number(e.target.value);ui();};$('format').onchange=e=>{canvas.width=e.target.value==='portrait'?720:1280;canvas.height=e.target.value==='portrait'?1280:720;canvas.classList.toggle('portrait',e.target.value==='portrait');ui();};$('position').oninput=e=>{stop();manual.position=Number(e.target.value)/100;ui();};$('state').onchange=e=>{stop();manual.state=e.target.value;if(time<8)time=8;ui();};$('angle').onchange=e=>{stop();manual.angle=Number(e.target.value);if(time<16)time=16;ui();};$('rotation').oninput=e=>{stop();manual.rotation=Number(e.target.value)*Math.PI/180;ui();};$('language').onchange=async e=>{const selected=e.target.value;{const loc=await fetch(`locales/${selected}.json`).then(r=>r.json());await configure({locale:selected,stories:Object.fromEntries(Object.entries(baseStories).map(([k,v])=>[k,{...v,...loc.stories[k]}])),labels:loc.labels});}};$('plane').onchange=e=>{stop();manual.plane=Number(e.target.value);ui();};$('reset').onclick=()=>{stop();manual={};$('rotation').value=0;$('angle').value=0;ui();};document.querySelectorAll('[data-tour]').forEach(b=>b.onclick=()=>select(b.dataset.tour).catch(showError));
function showError(e){$('status').textContent=`Could not load local tour: ${e.message}. Serve this folder over localhost.`;console.error(e);}
const ready=select(new URLSearchParams(location.search).get('tour')||'segmentation').then(()=>document.fonts.ready);window.tourApp={ready,select,configure,seek(t){stop();manual={};time=t;ui();},renderFrame(t,w,h){stop();manual={};draw(t,w,h);return canvas.toDataURL('image/png');},renderStill(t,w,h,type='image/jpeg',quality=.9){stop();manual={};draw(t,w,h);return canvas.toDataURL(type,quality);},getState(){return{id,time,playing,manual,width:canvas.width,height:canvas.height,step:chosenStep};}};ready.catch(showError);requestAnimationFrame(tick);
