// Generated by python -m tb3_medical.presentation_contracts. Do not edit.
export type VisualRole = "input" | "helpers" | "answer";
export type TaskTab = "overview" | "requirements" | "examples" | "sources";
export type BrowseView = "capability" | "repository";
export type ResearchLane = "tasks" | "supporting" | "all";
export type BriefField = "goal" | "value" | "raw" | "helpers" | "output" | "challenge" | "spec" | "tools" | "score" | "reference" | "families" | "gap" | "case_note";
export interface Illustration {
  kind: string;
  input: string;
  output: string;
  caption: string;
  subject?: string;
  target?: string;
  scene_variant?: string;
  mask_mode?: string;
  input_form?: string;
  initial_candidate?: boolean;
  labels?: Array<string>;
}
export interface Study {
  id: string;
  title: string;
  scope: string;
  tasks: Array<string>;
  protocol: string;
  record_path: string;
}
export interface Condition {
  name: string;
  helper: string;
  remaining: string;
}
export interface Visuals {
  input: string;
  helpers: string;
  answer: string;
}
export interface LocalizedBrief {
  title: string;
  goal: string;
  value: string;
  raw: string;
  helpers: string;
  output: string;
  challenge: string;
  spec: string;
  tools: string;
  score: string;
  reference: string;
  families: string;
  gap: string;
  case_note: string;
  variants: Array<Condition>;
  sources: Array<[string, string]>;
  visuals: Visuals;
  html: Partial<Record<"goal" | "value" | "raw" | "helpers" | "output" | "challenge" | "spec" | "tools" | "score" | "reference" | "families" | "gap" | "case_note", string>>;
  stages: Array<string>;
  missing_media: Array<string>;
}
export interface TaskEntry {
  id: string;
  title: string;
  repo: string;
  repository_id?: string;
  category: string;
  role?: string;
  agent_work: string;
  modalities: Array<string>;
  owner_group?: string;
  operations?: Array<string>;
  task_family?: string;
  nav_group?: string;
  nav_label?: string;
  proposed?: boolean;
  goal: string;
  value: string;
  raw: string;
  helpers: string;
  output: string;
  challenge: string;
  spec: string;
  tools: string;
  score: string;
  reference: string;
  families: string;
  gap: string;
  case_note: string;
  variants: Array<Condition>;
  sources: Array<[string, string]>;
  visuals: Visuals;
  html?: Partial<Record<"goal" | "value" | "raw" | "helpers" | "output" | "challenge" | "spec" | "tools" | "score" | "reference" | "families" | "gap" | "case_note", string>>;
  illustration?: Illustration;
  missing_media?: Array<string>;
  example_case_id?: string;
  studies?: Array<Study>;
  stages?: Array<string>;
  locales?: Record<string, LocalizedBrief>;
}
export interface CaseFact {
  value: string | number;
  label: string;
}
export interface CaseContext {
  label?: string;
  facts?: Array<CaseFact>;
  source?: string;
}
export interface InventoryItem {
  id: string;
  title: string;
  brief_id?: string;
  kind: string;
  definition: string;
  condition: string;
  condition_index?: number;
  family?: string;
  url: string;
  brief_scope_note?: string;
  case_context?: CaseContext;
}
export interface RepositoryInventory {
  id: string;
  items: Array<InventoryItem>;
  coverage: string;
  observed_on: string;
  commit: string;
}
export interface LocalSource {
  sha256?: string;
  bytes?: number;
  base64?: string;
  content?: string;
  unavailable?: string;
}
export interface SourceDigest {
  path: string;
  sha256: string;
}
export interface SnapshotPanel {
  role: "input" | "reference" | "metadata";
  caption: string;
  image_url?: string;
  text?: string;
  path?: string;
}
export interface DatasetSnapshot {
  sample_id: string;
  status: "paired" | "input-only" | "reference-only" | "unavailable";
  summary: string;
  panels: Array<SnapshotPanel>;
  reference_note: string;
  sources: Array<SourceDigest>;
}
export interface SampleReceipt {
  path: string;
  sha256: string;
  pointer?: string;
}
export interface SampleSet {
  label: string;
  role: string;
  sample_ids: Array<string>;
  note: string;
  receipt: SampleReceipt;
}
export interface DatasetExperiment {
  id: string;
  title: string;
}
export interface SourceLink {
  path: string;
  label: string;
}
export interface DatasetLocalized {
  title: string;
  summary: string;
  modality: string;
  sample_unit: string;
  image_description: string;
  annotation_description: string;
  reference_note: string;
  version_note: string;
  terms_note: string;
  access_note: string;
  documentation_gaps: Array<string>;
  sample_set_notes: Array<string>;
  snapshot_summary: string;
  snapshot_reference_note: string;
  snapshot_captions: Array<string>;
}
export interface DatasetRecord {
  id: string;
  title: string;
  modality: string;
  summary: string;
  image_description: string;
  annotation_description: string;
  sample_unit: string;
  reference_note: string;
  sample_sets: Array<SampleSet>;
  task_ids: Array<string>;
  experiments: Array<DatasetExperiment>;
  links?: Array<SourceLink>;
  version_note: string;
  terms_note: string;
  access_note?: string;
  documentation_gaps?: Array<string>;
  record_path: string;
  locales?: Record<string, DatasetLocalized>;
  [key: string]: unknown;
}
export interface CategoryInfo {
  title: string;
  description: string;
}
export interface Taxonomy {
  categories?: Record<string, CategoryInfo>;
  roles?: Record<string, string>;
  agent_work?: Record<string, string>;
  modalities?: Record<string, string>;
}
export interface TaskFamily {
  title: string;
  selector: string;
}
export interface PresentationContext {
  home_url?: string;
  home_label?: string;
  story_urls?: Record<string, string>;
}
export interface DatasetCoverage {
  experiments?: number;
  scope?: string;
}
export interface DatasetCollection {
  records: Array<DatasetRecord>;
  previews?: Record<string, DatasetSnapshot>;
  coverage: DatasetCoverage;
}
export interface Inventory {
  repositories?: Array<RepositoryInventory>;
}
export interface ExplorerData {
  schema_version: 1;
  title?: string;
  entries: Array<TaskEntry>;
  inventory: Inventory;
  taxonomy: Taxonomy;
  task_families?: Record<string, TaskFamily>;
  repository_contexts?: Record<string, string>;
  local_sources: Record<string, LocalSource>;
  presentation_context?: PresentationContext;
  datasets?: DatasetCollection;
}
export interface VocabularyTerm {
  label: string;
  definition: string;
}
export interface VocabularyAxis {
  values: Record<string, VocabularyTerm>;
}
export interface OverviewVocabulary {
  axes: Record<string, VocabularyAxis>;
  context_badges: Record<string, VocabularyTerm>;
  display_rules: Record<string, string | Array<string>>;
}
export interface ReviewFlag {
  experiment_id: string;
  assessment: string;
  reason: string;
}
export interface RecordCurrent {
  review_flags?: Array<ReviewFlag>;
  [key: string]: unknown;
}
export interface PortableLink {
  label: string;
  url?: string | null;
}
export interface ResearchRecord {
  id: string;
  kind: string;
  current: RecordCurrent;
  portable_links?: Array<PortableLink>;
  experiment_ids?: Array<string>;
  [key: string]: unknown;
}
export interface OverviewData {
  schema_version: 1;
  records: Array<ResearchRecord>;
  vocabulary: OverviewVocabulary;
  task_explorer_url?: string | null;
  local_media: boolean;
}
