// Generated by python -m tb3_medical.presentation_contracts. Do not edit.
export type VisualRole = "input" | "helpers" | "answer";
export type TaskTab = "overview" | "requirements" | "examples" | "sources";
export type BrowseView = "capability" | "repository";
export type ResearchLane = "tasks" | "supporting" | "all";
export type BriefField = "goal" | "value" | "raw" | "helpers" | "output" | "challenge" | "spec" | "tools" | "score" | "reference" | "families" | "gap" | "case_note";
export type StoryPlan = RouteStoryPlan | TopologyPlan | CorrespondencePlan | MaterialPlan | LongitudinalPlan | MultiscalePlan | InversePlan | EditPlan | AnatomyPlan | IdentityPlan | PrototypeIdentityPlan | LongitudinalCtRevisedPlan | LongitudinalCtOriginalPlan | LongitudinalMriPlan | TigerContextPlan | HubmapInventoryPlan | TopbrainScreenPlan | AirwayRepairPlan | VesselSourcePlan | ResectPilotPlan | ResectPlan | RegistrationAnalysisPlan | CtContextPlan | HistorySourcingPlan | MriImporterPlan | LocalizedCtPlan | AneurysmPlan | SegmentationCalibrationPlan | DentalV3Plan | DentalV2Plan | DentalOriginalPlan | CtOrganPlan | NamedLandmarksPlan | ClinicalCavityPlan | RespiratoryPlan | CurationPlan | MaskScreenPlan | MixedTissuePlan;
export interface StoryBeat {
  id: string;
  duration: number;
  caption: string;
  narration: string;
  visual: string;
  context: [number, number];
  route: [number, number];
  ribbon: [number, number];
  cursor: [number, number];
  unfold: [number, number];
  output: [number, number];
  startFrame: number;
  endFrame: number;
}
export interface RouteStoryPlan {
  schema: 1;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  recipe: "route-unfold-v1";
  asset_pack: "tb3-route-kit-v1";
  fps: number;
  reference_policy: "no-reference-assets";
  source_class: "procedural-teaching";
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  scope: string;
  beats: Array<StoryBeat>;
}
export interface ExpansionPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
}
export interface ExpansionBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
}
export interface TopologyChannels {
  focus: [number, number];
  trace: [number, number];
  inventory: [number, number];
}
export interface TopologyBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: TopologyChannels;
}
export interface TopologyPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "topology-v1";
  operation: "ordered-path" | "edge-inventory";
  beats: Array<TopologyBeat>;
}
export interface CorrespondenceChannels {
  transform: [number, number];
  query: [number, number];
  residual: [number, number];
}
export interface CorrespondenceBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  show_deformed_target: boolean;
  channels: CorrespondenceChannels;
}
export interface CorrespondencePlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "correspondence-v1";
  beats: Array<CorrespondenceBeat>;
}
export interface MaterialChannels {
  phase: [number, number];
  markers: [number, number];
  alternative: [number, number];
}
export interface MaterialBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: MaterialChannels;
}
export interface MaterialPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "shape-material-v1";
  beats: Array<MaterialBeat>;
}
export interface LongitudinalChannels {
  visits: [number, number];
  links: [number, number];
  coverage: [number, number];
}
export interface LongitudinalBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: LongitudinalChannels;
}
export interface LongitudinalPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "longitudinal-v1";
  beats: Array<LongitudinalBeat>;
}
export interface MultiscaleChannels {
  viewport: [number, number];
  selections: [number, number];
  coverage: [number, number];
  outputs: [number, number];
}
export interface MultiscaleBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: MultiscaleChannels;
}
export interface MultiscalePlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "multiscale-v1";
  operation: "coordinate-navigation" | "supplied-patches" | "annotation-coverage";
  beats: Array<MultiscaleBeat>;
}
export interface InverseChannels {
  observations: [number, number];
  reconstruction: [number, number];
  residual: [number, number];
}
export interface InverseBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: InverseChannels;
}
export interface InversePlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "inverse-v1";
  beats: Array<InverseBeat>;
  acquisition: "ct-parallel" | "mri-cartesian";
}
export interface EditChannels {
  domain: [number, number];
  correction: [number, number];
  control: [number, number];
}
export interface EditBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: EditChannels;
}
export interface EditPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "local-edit-v1";
  beats: Array<EditBeat>;
}
export interface AnatomyChannels {
  focus: [number, number];
  evidence: [number, number];
  output: [number, number];
}
export interface AnatomyBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: AnatomyChannels;
}
export interface AnatomyPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "anatomy-audit-v1";
  beats: Array<AnatomyBeat>;
}
export interface IdentityChannels {
  focus: [number, number];
  inventory: [number, number];
  reveal: [number, number];
}
export interface IdentityBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: IdentityChannels;
}
export interface IdentityPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "anatomy-identity-v1";
  beats: Array<IdentityBeat>;
}
export interface PrototypeIdentityPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "prototype-identity-v1";
  beats: Array<IdentityBeat>;
}
export interface AirwayRepairChannels {
  view: [number, number];
  reference: [number, number];
  output: [number, number];
}
export interface AirwayRepairBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: AirwayRepairChannels;
  scene: "inputs" | "inspect" | "repair" | "route" | "cpr" | "reference" | "controls" | "comparison" | "limits";
}
export interface AirwayRepairPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "airway-repair-v1";
  beats: Array<AirwayRepairBeat>;
}
export interface LongitudinalCtRevisedChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface LongitudinalCtRevisedBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: LongitudinalCtRevisedChannels;
  scene: "inputs" | "rules" | "partition" | "inventory" | "size" | "context" | "decisions" | "newfocus" | "events" | "comparison" | "output" | "limits";
}
export interface LongitudinalCtRevisedPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "longitudinal-ct-revised-v1";
  beats: Array<LongitudinalCtRevisedBeat>;
}
export interface LongitudinalCtOriginalChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface LongitudinalCtOriginalBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: LongitudinalCtOriginalChannels;
  scene: "inputs" | "instances" | "partition" | "focus" | "matching" | "links" | "events" | "results" | "output" | "limits";
}
export interface LongitudinalCtOriginalPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "longitudinal-ct-original-v1";
  beats: Array<LongitudinalCtOriginalBeat>;
}
export interface LongitudinalMriChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface LongitudinalMriBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: LongitudinalMriChannels;
  scene: "inputs" | "locate" | "phases" | "sequences" | "measure" | "change" | "reference" | "output" | "forecast" | "limits";
}
export interface LongitudinalMriPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "longitudinal-mri-v1";
  beats: Array<LongitudinalMriBeat>;
}
export interface TigerContextChannels {
  view: [number, number];
  reference: [number, number];
}
export interface HubmapInventoryChannels {
  view: [number, number];
  reference: [number, number];
}
export interface TigerContextBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: TigerContextChannels;
  scene: "inputs" | "conditions" | "tissue" | "cells" | "assign" | "coordinates" | "area" | "density" | "output" | "limits";
}
export interface TigerContextPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "tiger-context-v1";
  beats: Array<TigerContextBeat>;
}
export interface HubmapInventoryBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: HubmapInventoryChannels;
  scene: "inputs" | "helpers" | "detail" | "outline" | "coordinates" | "duplicate" | "area" | "inventory" | "conditions" | "limits";
}
export interface HubmapInventoryPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "hubmap-inventory-v1";
  beats: Array<HubmapInventoryBeat>;
}
export interface TopbrainScreenChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface TopbrainScreenBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: TopbrainScreenChannels;
  scene: "inputs" | "cohort" | "variants" | "contacts" | "parent" | "calibration" | "cpr" | "admission" | "limits";
}
export interface TopbrainScreenPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "topbrain-screen-v1";
  beats: Array<TopbrainScreenBeat>;
}
export interface VesselSourceChannels {
  scan: [number, number];
  reference: [number, number];
  output: [number, number];
}
export interface VesselSourceBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: VesselSourceChannels;
  scene: "sources" | "states" | "inspect" | "contacts" | "nodes" | "contract" | "admission" | "limits";
}
export interface VesselSourcePlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "vessel-source-v1";
  beats: Array<VesselSourceBeat>;
}
export interface ResectPilotChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface ResectPilotBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: ResectPilotChannels;
  scene: "inputs" | "cue" | "inspect" | "search" | "output" | "reference" | "controls" | "limits";
}
export interface ResectPilotPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "resect-pilot-v1";
  beats: Array<ResectPilotBeat>;
}
export interface ResectChannels {
  reference: [number, number];
  scan: [number, number];
  helper: [number, number];
  output: [number, number];
}
export interface ResectBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: ResectChannels;
  scene: "inputs" | "frame" | "inspect" | "helpers" | "output" | "reference" | "cases" | "limits";
}
export interface ResectPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "resect-correspondence-v1";
  beats: Array<ResectBeat>;
}
export interface RegistrationAnalysisChannels {
  reference: [number, number];
  bounds: [number, number];
  curve: [number, number];
}
export interface RegistrationAnalysisBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: RegistrationAnalysisChannels;
  scene: "input" | "replay" | "composition" | "support" | "objective" | "context" | "repeats" | "limits";
}
export interface RegistrationAnalysisPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "registration-analysis-v1";
  beats: Array<RegistrationAnalysisBeat>;
}
export interface CtContextChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface CtContextBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: CtContextChannels;
  scene: "inputs" | "headers" | "liver" | "surgery" | "fields" | "reference" | "validator" | "limits";
}
export interface CtContextPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "ct-context-v1";
  beats: Array<CtContextBeat>;
}
export interface HistorySourcingChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface HistorySourcingBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: HistorySourcingChannels;
  scene: "retrieval" | "excerpts" | "classification" | "candidates" | "lineage" | "controls" | "reference" | "gap" | "limits";
}
export interface HistorySourcingPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "history-sourcing-v1";
  beats: Array<HistorySourcingBeat>;
}
export interface MriImporterChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface MriImporterBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: MriImporterChannels;
  scene: "inputs" | "ordinals" | "association" | "geometry" | "placement" | "outputs" | "reference" | "controls" | "trace" | "limits";
}
export interface MriImporterPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "mri-importer-v1";
  beats: Array<MriImporterBeat>;
}
export interface LocalizedCtChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface LocalizedCtBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: LocalizedCtChannels;
  scene: "inputs" | "rules" | "axial" | "orthogonal" | "serial" | "judgments" | "outputs" | "reference" | "scoring" | "context" | "limits";
}
export interface LocalizedCtPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "localized-ct-v1";
  beats: Array<LocalizedCtBeat>;
}
export interface AneurysmChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface AneurysmBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: AneurysmChannels;
  scene: "inputs" | "projections" | "slabs" | "candidate" | "depth" | "outputs" | "reference" | "miss" | "coverage" | "negative" | "matching" | "limits";
}
export interface AneurysmPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "aneurysm-localization-v1";
  beats: Array<AneurysmBeat>;
}
export interface SegmentationCalibrationChannels {
  view: [number, number];
  condition: [number, number];
  box: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface SegmentationCalibrationBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: SegmentationCalibrationChannels;
  scene: "inputs" | "sampling" | "boxes" | "preprocess" | "outputs" | "reference" | "sensitivity" | "duodenum" | "controls" | "metrics" | "latency" | "backend" | "limits";
}
export interface SegmentationCalibrationPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "segmentation-calibration-v1";
  beats: Array<SegmentationCalibrationBeat>;
}
export interface DentalV3Channels {
  view: [number, number];
  helper: [number, number];
  transfer: [number, number];
  output: [number, number];
  reference: [number, number];
  stage: [number, number];
}
export interface DentalV3Beat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: DentalV3Channels;
  scene: "inputs" | "contract" | "example" | "transfer" | "outputs" | "shape" | "metrics" | "pulp-gain" | "pulp-loss" | "pulp-reach" | "canal-crop" | "canal-extent" | "limits";
}
export interface DentalV3Plan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "dental-v3-v1";
  beats: Array<DentalV3Beat>;
}
export interface DentalV2Channels {
  view: [number, number];
  helper: [number, number];
  transfer: [number, number];
  output: [number, number];
  reference: [number, number];
  stage: [number, number];
}
export interface DentalV2Beat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: DentalV2Channels;
  scene: "inputs" | "contract" | "example" | "transfer" | "outputs" | "identity" | "metrics" | "pulp-rule" | "pulp-contents" | "pulp-clip" | "canals" | "small-canals" | "limits";
}
export interface DentalV2Plan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "dental-v2-v1";
  beats: Array<DentalV2Beat>;
}
export interface DentalOriginalChannels {
  diagnostic: [number, number];
  gate: [number, number];
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface DentalOriginalBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: DentalOriginalChannels;
  scene: "inputs" | "contract" | "method" | "output" | "reference" | "diagnostic" | "metrics" | "canals" | "restorations" | "pulp" | "omissions" | "limits";
}
export interface DentalOriginalPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "dental-original-v1";
  beats: Array<DentalOriginalBeat>;
}
export interface CtOrganChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface CtOrganBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: CtOrganChannels;
  scene: "inputs" | "contract" | "polygon" | "tool" | "output" | "reference" | "regressions" | "inventory" | "comparison" | "slices" | "limits";
}
export interface CtOrganPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "ct-organ-v1";
  beats: Array<CtOrganBeat>;
}
export interface NamedLandmarksChannels {
  view: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface NamedLandmarksBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: NamedLandmarksChannels;
  scene: "inputs" | "coordinates" | "search" | "output" | "reference" | "availability" | "condyle" | "mri" | "counterexample" | "comparison" | "conditions" | "limits";
}
export interface NamedLandmarksPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "named-landmarks-v1";
  beats: Array<NamedLandmarksBeat>;
}
export interface ClinicalCavityChannels {
  phase: [number, number];
  helper: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface ClinicalCavityBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: ClinicalCavityChannels;
  scene: "inputs" | "initial" | "tracking" | "reference" | "patient" | "preserved" | "static" | "shift" | "judgment" | "output";
}
export interface ClinicalCavityPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "clinical-cavity-v1";
  beats: Array<ClinicalCavityBeat>;
}
export interface RespiratoryChannels {
  depth: [number, number];
  output: [number, number];
  reference: [number, number];
}
export interface RespiratoryBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: RespiratoryChannels;
  scene: "inputs" | "frame" | "depth" | "output" | "reference" | "judgment" | "conditions" | "limits";
}
export interface RespiratoryPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "respiratory-v1";
  beats: Array<RespiratoryBeat>;
}
export interface CurationChannels {
  reference: [number, number];
  focus: [number, number];
}
export interface CurationBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: CurationChannels;
  scene: "pair" | "preservation" | "overlap" | "calibration" | "reserve" | "ambiguity" | "admission";
}
export interface CurationPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "anatomy-curation-v1";
  beats: Array<CurationBeat>;
}
export interface MaskScreenChannels {
  measure: [number, number];
  prediction: [number, number];
  reference: [number, number];
  focus: [number, number];
}
export interface MaskScreenBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: MaskScreenChannels;
  scene: "context" | "ribs-32" | "ribs-74" | "organs-32" | "admission";
}
export interface MaskScreenPlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "mask-screen-v1";
  beats: Array<MaskScreenBeat>;
}
export interface MixedTissueChannels {
  conditions: Array<number>;
  plane: Array<number>;
  overlay: Array<number>;
  reference: Array<number>;
  witness: Array<number>;
}
export interface MixedTissueBeat {
  id: string;
  frames: number;
  caption: string;
  narration: string;
  visual: string;
  cut: "continuous" | "intentional-cut";
  startFrame: number;
  endFrame: number;
  channels: MixedTissueChannels;
}
export interface MixedTissuePlan {
  schema: 2;
  id: string;
  title: string;
  locale: "en";
  purpose: string;
  scope: string;
  asset_pack: string;
  source_class: "procedural-teaching" | "source-derived-teaching";
  reference_policy: "no-reference-assets" | "reader-reference-reveal";
  fps: number;
  source_locators: Array<string>;
  durationFrames: number;
  source_sha256: string;
  asset_manifest_sha256: string;
  dependencies: Record<string, string>;
  recipe: "mixed-tissue-v1";
  beats: Array<MixedTissueBeat>;
}
export interface Illustration {
  story_id?: string;
  kind: string;
  input: string;
  output: string;
  caption: string;
  subject?: string;
  target?: string;
  scene_variant?: string;
  mask_mode?: string;
  input_form?: string;
  initial_candidate?: boolean;
  labels?: Array<string>;
}
export interface Study {
  id: string;
  title: string;
  scope: string;
  tasks: Array<string>;
  protocol: string;
  record_path: string;
}
export interface Condition {
  name: string;
  helper: string;
  remaining: string;
}
export interface Visuals {
  input: string;
  helpers: string;
  answer: string;
}
export interface LocalizedBrief {
  title: string;
  goal: string;
  value: string;
  raw: string;
  helpers: string;
  output: string;
  challenge: string;
  spec: string;
  tools: string;
  score: string;
  reference: string;
  families: string;
  gap: string;
  case_note: string;
  variants: Array<Condition>;
  sources: Array<[string, string]>;
  visuals: Visuals;
  html: Partial<Record<"goal" | "value" | "raw" | "helpers" | "output" | "challenge" | "spec" | "tools" | "score" | "reference" | "families" | "gap" | "case_note", string>>;
  stages: Array<string>;
  missing_media: Array<string>;
}
export interface TaskEntry {
  id: string;
  title: string;
  repo: string;
  repository_id?: string;
  category: string;
  role?: string;
  agent_work: string;
  modalities: Array<string>;
  owner_group?: string;
  operations?: Array<string>;
  task_family?: string;
  nav_group?: string;
  nav_label?: string;
  proposed?: boolean;
  goal: string;
  value: string;
  raw: string;
  helpers: string;
  output: string;
  challenge: string;
  spec: string;
  tools: string;
  score: string;
  reference: string;
  families: string;
  gap: string;
  case_note: string;
  variants: Array<Condition>;
  sources: Array<[string, string]>;
  visuals: Visuals;
  html?: Partial<Record<"goal" | "value" | "raw" | "helpers" | "output" | "challenge" | "spec" | "tools" | "score" | "reference" | "families" | "gap" | "case_note", string>>;
  illustration?: Illustration;
  missing_media?: Array<string>;
  example_case_id?: string;
  studies?: Array<Study>;
  stages?: Array<string>;
  locales?: Record<string, LocalizedBrief>;
}
export interface CaseFact {
  value: string | number;
  label: string;
}
export interface CaseContext {
  label?: string;
  facts?: Array<CaseFact>;
  source?: string;
}
export interface InventoryItem {
  id: string;
  title: string;
  brief_id?: string;
  kind: string;
  definition: string;
  condition: string;
  condition_index?: number;
  family?: string;
  url: string;
  brief_scope_note?: string;
  case_context?: CaseContext;
}
export interface RepositoryInventory {
  id: string;
  items: Array<InventoryItem>;
  coverage: string;
  observed_on: string;
  commit: string;
}
export interface LocalSource {
  sha256?: string;
  bytes?: number;
  base64?: string;
  content?: string;
  unavailable?: string;
}
export interface SourceDigest {
  path: string;
  sha256: string;
}
export interface SnapshotPanel {
  role: "input" | "reference" | "metadata";
  caption: string;
  image_url?: string;
  text?: string;
  path?: string;
}
export interface DatasetSnapshot {
  sample_id: string;
  status: "paired" | "input-only" | "reference-only" | "unavailable";
  summary: string;
  panels: Array<SnapshotPanel>;
  reference_note: string;
  sources: Array<SourceDigest>;
}
export interface SampleReceipt {
  path: string;
  sha256: string;
  pointer?: string;
}
export interface SampleSet {
  label: string;
  role: string;
  sample_ids: Array<string>;
  note: string;
  receipt: SampleReceipt;
}
export interface DatasetExperiment {
  id: string;
  title: string;
}
export interface SourceLink {
  path: string;
  label: string;
}
export interface DatasetLocalized {
  title: string;
  summary: string;
  modality: string;
  sample_unit: string;
  image_description: string;
  annotation_description: string;
  reference_note: string;
  version_note: string;
  terms_note: string;
  access_note: string;
  documentation_gaps: Array<string>;
  sample_set_notes: Array<string>;
  snapshot_summary: string;
  snapshot_reference_note: string;
  snapshot_captions: Array<string>;
}
export interface DatasetRecord {
  id: string;
  title: string;
  modality: string;
  summary: string;
  image_description: string;
  annotation_description: string;
  sample_unit: string;
  reference_note: string;
  sample_sets: Array<SampleSet>;
  task_ids: Array<string>;
  experiments: Array<DatasetExperiment>;
  links?: Array<SourceLink>;
  version_note: string;
  terms_note: string;
  access_note?: string;
  documentation_gaps?: Array<string>;
  record_path: string;
  locales?: Record<string, DatasetLocalized>;
  [key: string]: unknown;
}
export interface CategoryInfo {
  title: string;
  description: string;
}
export interface Taxonomy {
  categories?: Record<string, CategoryInfo>;
  roles?: Record<string, string>;
  agent_work?: Record<string, string>;
  modalities?: Record<string, string>;
}
export interface TaskFamily {
  title: string;
  selector: string;
}
export interface PresentationContext {
  home_url?: string;
  home_label?: string;
  story_urls?: Record<string, string>;
}
export interface DatasetCoverage {
  experiments?: number;
  scope?: string;
}
export interface DatasetCollection {
  records: Array<DatasetRecord>;
  previews?: Record<string, DatasetSnapshot>;
  coverage: DatasetCoverage;
}
export interface Inventory {
  repositories?: Array<RepositoryInventory>;
}
export interface ExplorerData {
  explanation_stories?: Record<string, RouteStoryPlan | TopologyPlan | CorrespondencePlan | MaterialPlan | LongitudinalPlan | MultiscalePlan | InversePlan | EditPlan | AnatomyPlan | IdentityPlan | PrototypeIdentityPlan | LongitudinalCtRevisedPlan | LongitudinalCtOriginalPlan | LongitudinalMriPlan | TigerContextPlan | HubmapInventoryPlan | TopbrainScreenPlan | AirwayRepairPlan | VesselSourcePlan | ResectPilotPlan | ResectPlan | RegistrationAnalysisPlan | CtContextPlan | HistorySourcingPlan | MriImporterPlan | LocalizedCtPlan | AneurysmPlan | SegmentationCalibrationPlan | DentalV3Plan | DentalV2Plan | DentalOriginalPlan | CtOrganPlan | NamedLandmarksPlan | ClinicalCavityPlan | RespiratoryPlan | CurationPlan | MaskScreenPlan | MixedTissuePlan>;
  schema_version: 1;
  title?: string;
  entries: Array<TaskEntry>;
  inventory: Inventory;
  taxonomy: Taxonomy;
  task_families?: Record<string, TaskFamily>;
  repository_contexts?: Record<string, string>;
  local_sources: Record<string, LocalSource>;
  presentation_context?: PresentationContext;
  datasets?: DatasetCollection;
}
export interface VocabularyTerm {
  label: string;
  definition: string;
}
export interface VocabularyAxis {
  values: Record<string, VocabularyTerm>;
}
export interface OverviewVocabulary {
  axes: Record<string, VocabularyAxis>;
  context_badges: Record<string, VocabularyTerm>;
  display_rules: Record<string, string | Array<string>>;
}
export interface ReviewFlag {
  experiment_id: string;
  assessment: string;
  reason: string;
}
export interface RecordCurrent {
  review_flags?: Array<ReviewFlag>;
  [key: string]: unknown;
}
export interface PortableLink {
  label: string;
  url?: string | null;
}
export interface ResearchRecord {
  id: string;
  kind: string;
  current: RecordCurrent;
  portable_links?: Array<PortableLink>;
  experiment_ids?: Array<string>;
  [key: string]: unknown;
}
export interface OverviewData {
  schema_version: 1;
  records: Array<ResearchRecord>;
  vocabulary: OverviewVocabulary;
  task_explorer_url?: string | null;
  local_media: boolean;
}
